### ISSUE TITLE
Uncaught (in promise) GVLError: Cannot read property 'purposes' of null

### ISSUE THREAD

**Issue by adityamishraofficial** [InteractiveAdvertisingBureau/iabtcf#14]
I am getting an error while passing vendor list  ( GVLError: Cannot read property 'purposes' of null )

     GVL.baseUrl = 'http://localhost:3000/vendorlist.json';
        const tcModel = new TCModel(new GVL());
        tcModel.gvl.readyPromise.then(() => {
            const encodedString = TCString.encode(tcModel);
            console.log(encodedString); // TC string encoded begins with 'C'
        });

**Comment by chrispaterson** [comment]
Change
`GVL.baseUrl = 'http://localhost:3000/vendorlist.json';`

To

`GVL.baseUrl = 'http://localhost:3000/';`

Rename vendorlist.json to vendor-list.json 
Or set `‘GVL.latestFilename = ‘vendorlist.json’’`

**Comment by adityamishraofficial** [comment]
After the changes I am still getting error

Uncaught (in promise) GVLError: Cannot convert undefined or null to object

<img width="1130" alt="Screenshot 2020-07-17 at 10 36 00 AM" src="https://user-images.githubusercontent.com/47855476/87750520-512f1880-c819-11ea-83dc-236e4e198838.png">


```
 GVL.baseUrl = 'http://localhost:3000/';
        const tcModel = new TCModel(new GVL());
        tcModel.gvl.readyPromise.then(() => {
            const encodedString = TCString.encode(tcModel);
            console.log(encodedString); // TC string encoded begins with 'C'
        });
```
And now My vendor file name is **vendor-list.json**

**Comment by adityamishraofficial** [comment]
I am also trying this but still getting error

<img width="827" alt="Screenshot 2020-07-17 at 11 22 08 AM" src="https://user-images.githubusercontent.com/47855476/87753220-c271ca00-c81f-11ea-8f2f-e0099644fd8b.png">



```
 GVL.baseUrl = 'http://localhost:3000/';
        const gvl = new GVL("LATEST");
        gvl.readyPromise.then(() => {
            const tcModel = new TCModel(gvl);
            const encodedTCString = TCString.encode(tcModel);
            console.log(encodedTCString);
        });
```

**Comment by adityamishraofficial** [comment]
thanks man ...
