### ISSUE TITLE
Question regarding "BaseUrl" and implementation question

### ISSUE THREAD

**Issue by nihant7** [InteractiveAdvertisingBureau/iabtcf#2]
Hello,

Below I'm trying to generate a consent string using just purpose consent "1" but I'm not sure if this is the right way. I saved this file as "enc.ts"

Steps that I ran are below :
-------------------------------
1. **npm install @iabtcf/core --save**

2. **406  20/01/20 14:35:08 tsc enc.ts 
3. 407  20/01/20 14:35:15 node enc.js**
-------------------------------

and seeing the below error:
**NehaR-6LNVH2:@iabtcf nihantg$ node dec.js
/Users/nihantg/iab-tcf/node_modules/@iabtcf/core/lib/GVL.js:54
                throw new errors_1.GVLError('Invalid baseUrl!  You may not pull directly from vendorlist.consensu.org and must provide your own cache');
                ^

GVLError: Invalid baseUrl!  You may not pull directly from vendorlist.consensu.org and must provide your own cache
    at new GVLError (/Users/nihantg/iab-tcf/node_modules/@iabtcf/core/lib/errors/GVLError.js:19:28)
    at Function.set [as baseUrl] (/Users/nihantg/iab-tcf/node_modules/@iabtcf/core/lib/GVL.js:54:23)
    at Object.<anonymous> (/Users/nihantg/iab-tcf/node_modules/@iabtcf/dec.js:10:20)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11**
---------------------------------------------------------------------

**Below is "enc.ts"** :
import {TCString, TCModel, GVL} from '@iabtcf/core';

/**
 * With v2.0 of the TCF, CMPs are required to host their own vendor-list.json for
 * their client-side scripts to consume.  This GVL class follows the convention
 * outlined in the GVL URL Version scheme.  (latest at vendor-list.json and
 * version specific at archives/vendor-list-v{vendor-list-version}.json
 */
GVL.baseUrl = "https://vendorlist.consensu.org/v2/vendor-list.json";

// we'll get the latest GVL to encode this RTCString to
const gvl = new GVL("LATEST");

// have to wait for it to fetch the json
gvl.readyPromise.then(() => {

  const tcModel = new TCModel(gvl);
  tcModel.cmpVersion=1;
  tcModel.cmpId=7;
  tcModel.purposeConsents.set(1);
  tcModel.consentLanguage='en';
  const encodedTCString = TCString.encode(tcModel);

  /**
   * this will output a default all "no" encoded string to the console at the
   * lastest GVL version.
   */
  console.log(encodedTCString);
});

Please suggest me what can I do from here. A sample way of string generation example would also be handy. Thanks in advance

**Comment by chrispaterson** [comment]
You must host your own vendor-list.json https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/core#autoload-latest-vendor-listjson 

And you pass the base url to the vendor-list.json so if you host it at: https://mydomain.com/vendorlist/vendor-list.json

Your base url is https://mydomain.com/vendorlist
and your latest filename is vendor-list.json
